### ISSUE TITLE
superclass mismatch for class Task

### ISSUE THREAD

**Issue by bueti** [meilisearch/meilisearch-rails#101]
**Description**
I'm trying to add meilisearch to an existing Rails app. I've followed your [blog post](https://blog.meilisearch.com/how-to-integrate-an-extremely-fast-and-relevant-search-into-your-rails-app-using-meilisearch-and-react/) but after installing an enabling meilisearch-rails I get the following error:
```
F, [2022-01-23T08:20:09.249851 #1] FATAL -- : [cc86965b-0e6c-4b50-a197-53b73cea5c65]
TypeError - superclass mismatch for class Task:
  app/models/task.rb:33:in `<top (required)>'
  app/views/layouts/_header.html.erb:57
  app/views/layouts/application.html.erb:55
```

**Expected behavior**
No superclass mismatch :)

**Current behavior**
```
F, [2022-01-23T08:20:09.249851 #1] FATAL -- : [cc86965b-0e6c-4b50-a197-53b73cea5c65]
TypeError - superclass mismatch for class Task:
  app/models/task.rb:33:in `<top (required)>'
  app/views/layouts/_header.html.erb:57
  app/views/layouts/application.html.erb:55
```

**Environment (please complete the following information):**
- OS: ruby:2.6.9-alpine3.15
- MeiliSearch version: v0.25.2
- meilisearch-rails version: v0.4.0
- Rails version: 6.0.4.3

**Comment by brunoocasali** [comment]
Hello @bueti how are you?!

Could you share with me the content of your entire model `app/models/task.rb`?

**Comment by bueti** [comment]
@brunoocasali is there a way to share this with you privately? it's pretty big model and it's not opensource.

if there's something specific you are looking for I might be able to share that part.

**Comment by brunoocasali** [comment]
Yes, you could share with but before doing that...

I'm trying to understand what caused this behavior, so I'll ask you to try the old version of meilisearch, could you do that for me [meilisearch-rails release v0.3.0](https://github.com/meilisearch/meilisearch-rails/releases/tag/v0.3.0)? 

I have an educated guess about this problem: We unintentionally introduced this behavior after the addition of this file https://github.com/meilisearch/meilisearch-ruby/blob/9290118c751b5dc5e6e23eb39e5143d05da8818c/lib/meilisearch/task.rb#L7 (in the newly released ruby version which is a dependency from rails version you're currently using).

So to confirm this, if you can, please test using an older version of meilisearch-rails and meilisearch server `v0.24`.

**Comment by bueti** [comment]
@brunoocasali I think you guess is correct. Downgrading to v0.3.0 and v0.24.0 solved the issue.

**Comment by brunoocasali** [comment]
Cool, thanks @bueti I'll be working on a fix for this problem ASAP.

**Comment by brunoocasali** [comment]
Just to add for future researchers: 

This happens not only for the `Task` class but for `Client` ([and all the other classes defined here](https://github.com/meilisearch/meilisearch-ruby/tree/main/lib/meilisearch)) as well, and probably this should happen even in versions before the `meilisearch-ruby 0.17`.

**Comment by brunoocasali** [comment]
I couldn’t reproduce exactly your issue @bueti but I have some related problems in a brand new rails 6.1 project:

```rb
class Client < ApplicationRecord
  include MeiliSearch

  meilisearch
end
```

```rb
irb(main):004:0> Client.create(surname: "ADS", name: "asdjsa 1234")
irb(main):005:0> Client.search("12")
```
```bash
Traceback (most recent call last):
        1: from (irb):5
NoMethodError (undefined method `where' for MeiliSearch::Client:Class)
Did you mean?  when
```

Either way, I'm still working in a fix for it 😅

**Comment by bueti** [comment]
> Hey @bueti, could you try this branch `bug-fix/issue-101` in your app?
> 
> ```ruby
> gem 'meilisearch-rails', git: 'git@github.com:meilisearch/meilisearch-rails.git', branch: 'bug-fix/issue-101'
> ```
> 
> or if you have the shorthand
> 
> ```ruby
> gem 'meilisearch-rails', github: 'meilisearch/meilisearch-rails', branch: 'bug-fix/issue-101'
> ```

works like a charm! 👍

**Comment by brunoocasali** [comment]
@bueti [we released the new version](https://github.com/meilisearch/meilisearch-rails/releases/tag/v0.4.1) with this fix, please check them out!

**Comment by bueti** [comment]
works, thanks for the quick fix!
