### ISSUE TITLE
Custom Attributes does not returns on search

### ISSUE THREAD

**Issue by rodrigoodhin** [meilisearch/meilisearch-rails#134]
HI All,

I've try to use custom attributes on my model, but when a search, this field is not returned. The custom field is ok on meilisearch UI.

My Product Model

```
class Product < ApplicationRecord
  include MeiliSearch::Rails
  include MoneyRails::ActionViewExtension

  belongs_to :brand, optional: true, touch: true

  has_many :product_languages, dependent: :destroy
  after_save { product_languages.each(&:touch) }

  # MeiliSearch
  meilisearch force_utf8_encoding: true do
    attribute :id, :name, :short_description, :full_description
    attribute :product_languages do
      product_languages.pluck(:language, :name, :short_description, :full_description)
    end
    attribute :humanized_price do
      humanized_money price_to_customer
    end
    attribute :photo do
      Rails.application.routes.url_helpers.rails_representation_url(self.main_image.variant(resize: "600x600").processed, only_path: true) if self.main_image.attached?
    end
    attribute :brand do
      brand.name
    end

    displayed_attributes [:id, :name, :short_description, :full_description, :product_languages, :humanized_price, :photo, :brand]
    filterable_attributes [:id, :name, :language, :short_description, :full_description, :brand, :product_languages]
    sortable_attributes [:id, :name, :humanized_price, :brand]
  end
  after_touch :index!

  def will_save_change_to_humanized_price?
    will_save_change_to_cost_price_cents? || will_save_change_to_price_cents? || will_save_change_to_recommended_retail_price_cents? || will_save_change_to_default_shipping_cost_cents? || will_save_change_to_vat_cents?
  end

  def will_save_change_to_photo?
    will_save_change_to_main_image?
  end
end
```

Searching on rails console:
```
[56] pry(main)> p = Product.search('33074510115')
[57] pry(main)> p[0].photo
NoMethodError: undefined method `photo' for #<Product:0x00007f0bdd0eb588>
from /home/app/.rvm/gems/ruby-2.6.0/gems/activemodel-5.2.6/lib/active_model/attribute_methods.rb:430:in `method_missing'
[58] pry(main)> p[0].humanized_price
NoMethodError: undefined method `humanized_price' for #<Product:0x00007f0bdd0eb588>
Did you mean?  humanized_money
from /home/app/.rvm/gems/ruby-2.6.0/gems/activemodel-5.2.6/lib/active_model/attribute_methods.rb:430:in `method_missing'
[59] pry(main)> p[0].brand
  Brand Load (0.7ms)  SELECT  `brands`.* FROM `brands` WHERE `brands`.`id` = 15848592665 LIMIT 1
=> #<Brand:0x00007f0bdd3ddea8
 id: 15848592665,
 name: "SEVEN CREATIONS",
 url: "seven-creations",
 brand_id: nil,
 created_at: Sun, 13 Mar 2022 08:41:27 WET +00:00,
 updated_at: Sun, 13 Mar 2022 08:41:55 WET +00:00>
[60] pry(main)> 
```

The fields photo, humanized_price brand, are not returning as expected.

I'm doing something wrong or it's a bug?

**Comment by brunoocasali** [comment]
Hi @rodrigoodhin, thanks for using Meilisearch!

Your configuration seems to be ok to me, but I think you misunderstood the idea of these attributes, they are meant to be sent to the Meilisearch server during indexing and they became available to be searched/filtered and stuff.

But since we respond with an ActiveRecord object (in your case), we just don't have access to your custom attribute.

Example:

```rb
class Model < ActiveRecord::Base
  ...
  meilisearch do
    attribute :up_name do
      name.upcase
    end
  end 
end 

# Model.search('bar') 
# => ActiveRecord::Relation (with only your attributes defined in your database, in this case without `up_name`)

# Model.raw_search('bar') 
# => Array of hashes (with all the attributes Meilisearch index contains, in this case including `up_name`)
```

Ir order to accomplish what you want, I suppose you just need to do something like this:

```rb
class Model < ActiveRecord::Base
  ...
  meilisearch do
    attribute :up_name
  end 
  
  def up_name
      name.upcase
  end
end 
```

**Comment by rodrigoodhin** [comment]
Hi @brunoocasali ,

You are right.
By doing what you did, you solved my problem.
Thank you very much for your answer.
