### ISSUE TITLE
How can I use Meiliserch with vagrant?  How do I set up the url?

### ISSUE THREAD

**Issue by sandonemaki** [meilisearch/meilisearch-rails#211]
Hello.
I have set up a VirtualBox in a virtual environment on my Mac and am using Vagrant.
I set up Meiliserch's URL while looking at [sample](https://github.com/meilisearch/meilisearch-rails#configuration-), but when I do User.search("Yamada") in rails c Meiliserch seems to be going to check the local host address of the mac.
How can I use Meiliserch with vagrant?

```ruby
MeiliSearch::Rails.configuration = {
  meilisearch_url: '192.168.56.13:7700', # example: http://localhost:7700
  meilisearch_api_key: 'ENV["MEILI_MASTER_KEY"]', # ~/.bash_proflie
}
```
error:
/home/vagrant/Meilisearch_rails/vendor/bundle/ruby/3.1.0/gems/meilisearch-0.19.2/lib/meilisearch/http_request.rb:110:in `rescue in send_request': An error occurred while trying to connect to the MeiliSearch instance: Failed to open TCP connection to localhost:7700 (Connection refused - connect(2) for 127.0.0.1:7700) (MeiliSearch::CommunicationError)
/home/vagrant/.anyenv/envs/rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Failed to open TCP connection to localhost:7700 (Connection refused - connect(2) for 127.0.0.1:7700) (Errno::ECONNREFUSED)
/home/vagrant/.anyenv/envs/rbenv/versions/3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Connection refused - connect(2) for 127.0.0.1:7700 (Errno::ECONNREFUSED)

**Comment by sandonemaki** [comment]
Hello. 
Resolved.
It was due to the fact that the Meilisearch engine was not started.
