### ISSUE TITLE
Upgrading to 0.11.0 produces "The request was not processed in the expected time." repeatedly.

### ISSUE THREAD

**Issue by mech** [meilisearch/meilisearch-rails#329]
After upgrading to 0.11.0, I got blasted with this error on every mutation on my model.

```
The request was not processed in the expected time.

meilisearch-0.26.0/lib/meilisearch/task.rb:49:in `rescue in wait_for_task'
meilisearch-0.26.0/lib/meilisearch/task.rb:39:in `wait_for_task'
meilisearch-0.26.0/lib/meilisearch/client.rb:143:in `wait_for_task'
meilisearch-0.26.0/lib/meilisearch/client.rb:45:in `create_index!'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:264:in `block in initialize'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:316:in `log_or_throw'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:263:in `initialize'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:770:in `new'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:770:in `ms_ensure_init'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:548:in `block in ms_index!'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:544:in `each'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:544:in `map'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:544:in `ms_index!'
gems/meilisearch-rails-0.11.0/lib/meilisearch-rails.rb:928:in `ms_index!'
```

I must say due to the excessive indexing settings, I did mute it previously on my settings like so:

```ruby
meilisearch check_settings: false do
  # my indexing settings...
end
```

Not sure if this will interfere with the current version though.

**Comment by ellnix** [comment]
`check_settings: false` should not be required any more, `0.11` should have fixed the constant settings updates.

But it looks like the issue is caused by attempting to create an index synchronously which I didn't think would be a problem. I will make a PR once I reproduce this in a test.
